FROM alpine

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

RUN apk update && \
    apk add make automake gcc g++ subversion python3-dev cmd:pip3 gfortran openblas-dev lapack && \
    apk add py3-scipy && \
    pip3 install --no-cache-dir --upgrade -r /app/requirements.txt

COPY . /app

EXPOSE 8000

VOLUME data/ /app/data/

RUN python3 load_model.py
CMD ["uvicorn", "fastapi_app:app", "--host", "0.0.0.0", "--port", "8000"]
